CREATE TABLE IF NOT EXISTS notes (
  id TEXT PRIMARY KEY ,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  image BLOB,
  tag TEXT DEFAULT 'GENERAL',
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);